server:
  port: 9093

spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:9095

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate configuration
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
